services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "pgres"
      POSTGRES_PASSWORD: "pgres"
      POSTGRES_DB: "pgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: ./ds_webapp
      dockerfile: ./DOCKERFILE 
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy 
    command: ["poetry", "run", "app"]
    networks:
      - app-network
  
  frontend:
    build:
      context: ./ui
      dockerfile: ./Dockerfile 
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://app:5000


networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
