name: CI

on: [pull_request]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for containers to be healthy
        run: |
          echo "Waiting for DB and app to be healthy..."
          docker compose ps

      - name: Run Black formatting check
        run: docker compose exec app poetry run black --check --diff ds_webapp/

      - name: Run Pylint
        run: docker compose exec app poetry run pylint ds_webapp/

      - name: Tear down
        if: always()
        run: docker compose down
