name: CI

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Read YAML File
        run: cat config/workflow.yaml

      - name: Use YAML in a script
        run: |
          CONFIG=$(cat config/workflow.yaml)
          echo "Loaded config: $CONFIG"
